# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=2)),
                ('brand', models.CharField(max_length=20)),
                ('temp', models.CharField(max_length=3)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('outdoor', 'アウトドア'), ('amekaji', 'アメカジ'), ('kuranji', 'クランジ'), ('surf', 'サーフ'), ('salon', 'サロン'), ('street', 'ストリート'), ('sports', 'スポーツMIX'), ('toratto', 'トラット'), ('noomukoa', 'ノームコア'), ('business', 'ビジネス'), ('hiphop', 'ヒップホップ'), ('host', 'ホスト'), ('mode', 'モード'), ('rock', 'ロック'), ('onee', 'お姉'), ('girlish', 'ガーリッシュ'), ('gyaru', 'ギャル'), ('kireime', 'きれいめカジュアル'), ('gosurori', 'ゴスロリ'), ('marine', 'マリン'), ('harajuku', '原宿'), ('morigirl', '森ガール')], max_length=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('purpose', models.CharField(choices=[('date', 'デート'), ('party', 'パーティ'), ('outdoor', 'アウトドア'), ('nochoice', '選択なし')], max_length=10)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
