# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20170706_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women')], max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='purpose',
            field=models.CharField(choices=[('date', 'デート'), ('party', 'パーティ'), ('outdoor', 'アウトドア'), ('business', 'ビジネス'), ('nochoice', '選択なし')], max_length=10),
        ),
    ]
