# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 22:43
from __future__ import unicode_literals

import clothes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_auto_20170709_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=clothes.models.get_image_path, verbose_name='画像'),
        ),
    ]
