# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_auto_20170711_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='og_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
