# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_post_og_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='og_image',
        ),
    ]
